name: ocr
description: Your_description_here

# Publishing information goes here if applicable
publish_to: # Your publishing information

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.5+7
  google_mlkit_text_recognition: ^0.11.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Assets, fonts, and other configurations...
